services:
  tududi:
    build: .
    image: tududi:latest
    container_name: tududi
    env_file:
      - .env
    volumes:
      - ./tududi_db:/app/backend/db
      - ./uploads:/app/backend/uploads
    ports:
      - "3002:3002"
    restart: unless-stopped
