services:
    tududi:
        build: .
        image: tududi-local:latest
        container_name: tududi
        restart: always
        ports:
            - '3002:3002'
        env_file:
            - .env
        volumes:
            - ./tududi_db:/app/backend/db
            - ./tududi_uploads:/app/backend/uploads
        networks:
            - default
            - caddy-public-net

networks:
    default:
    caddy-public-net:
        external: true
